name: Ping Render Sites

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Ecommerce Website
        run: curl -s https://ecommerce-webiste-29k9.onrender.com/ > /dev/null

      - name: Ping Mail Me
        run: curl -s https://mail-me-2cm1.onrender.com/ > /dev/null

      - name: Ping Altivox Project
        run: curl -s https://altivox-project.onrender.com/ > /dev/null
