name: Ping Render Sites

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes
  workflow_dispatch:          # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Ecommerce Website
        run: curl -s https://community-tracker.onrender.com/

      - name: Ping Prompt Zuko Website
        run: curl -s https://prompt-zuko.onrender.com/

      - name: Ping Prompt Zuko Website
        run: curl -s https://microservice-traslational-api.onrender.com/docs/

