name: Ping Render Sites

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes
  workflow_dispatch:          # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ml content flagging
        run: curl -s https://content-moderation-ml.onrender.com/health/

      - name: Ping Translated Api Microservice
        run: curl -s https://microservice-traslational-api.onrender.com/docs/

